import type { AptitudeSection } from '@prisma/client';

/**
 * The shared aptitude bank every institution starts with.
 *
 * Written for this platform, not taken from any book or test paper. The shape
 * follows what campus first rounds actually test - quant, reasoning, verbal
 * and a little technical - so practice here transfers, but every question and
 * passage is original. Each has an explanation, because a practice question
 * that only says "wrong" teaches nothing.
 */
export interface BankQuestion {
  section: AptitudeSection;
  topic: string;
  difficulty: 1 | 2 | 3;
  stem: string;
  options: string[];
  answerIndex: number;
  explanation: string;
}

const PASSAGE =
  'Passage: A small bakery in Nashik began sending its unsold bread to a nearby shelter each evening. Within a year it was baking about a fifth less, because keeping track of what came back showed which loaves customers rarely bought. The owner says the donations began as charity but became the bakery’s most useful source of data.';

export const QUESTION_BANK: BankQuestion[] = [
  /* --- quant ------------------------------------------------------------ */
  { section: 'QUANT', topic: 'Percentages', difficulty: 1, stem: 'A shirt priced at ₹800 is sold at 15% off. What is the sale price?', options: ['₹640', '₹660', '₹680', '₹700'], answerIndex: 2, explanation: '15% of 800 is 120, so the price is 800 − 120 = ₹680.' },
  { section: 'QUANT', topic: 'Percentages', difficulty: 2, stem: 'A number is increased by 20% and the result is then decreased by 20%. What is the overall change?', options: ['No change', '4% decrease', '4% increase', '2% decrease'], answerIndex: 1, explanation: '100 → 120 → 96. The second 20% is taken from a bigger number, so the result is 4% lower than where you started.' },
  { section: 'QUANT', topic: 'Percentages', difficulty: 1, stem: 'In a batch of 120 students, 30% chose Mechanical. How many did not?', options: ['36', '80', '84', '90'], answerIndex: 2, explanation: '30% of 120 is 36, so 120 − 36 = 84 did not.' },
  { section: 'QUANT', topic: 'Profit and loss', difficulty: 1, stem: 'An item bought for ₹500 is sold for ₹600. What is the profit percentage?', options: ['10%', '16.67%', '20%', '25%'], answerIndex: 2, explanation: 'Profit is ₹100 on a cost of ₹500: 100 ÷ 500 = 20%. Profit % is always on the cost price.' },
  { section: 'QUANT', topic: 'Profit and loss', difficulty: 2, stem: 'An item is sold for ₹900 at a loss of 10%. What was its cost price?', options: ['₹990', '₹1,000', '₹1,010', '₹1,100'], answerIndex: 1, explanation: 'Selling at a 10% loss means 90% of cost = 900, so cost = 900 ÷ 0.9 = ₹1,000.' },
  { section: 'QUANT', topic: 'Profit and loss', difficulty: 3, stem: 'A shop marks an item at ₹1,000, gives a 10% discount, and still makes a 20% profit. What did the item cost the shop?', options: ['₹720', '₹750', '₹800', '₹810'], answerIndex: 1, explanation: 'Selling price = 1,000 − 10% = 900. That is 120% of cost, so cost = 900 ÷ 1.2 = ₹750.' },
  { section: 'QUANT', topic: 'Time and work', difficulty: 2, stem: 'A can finish a job in 10 days and B in 15 days. How long do they take working together?', options: ['5 days', '6 days', '7.5 days', '12.5 days'], answerIndex: 1, explanation: 'Per day, A does 1/10 and B does 1/15. Together 1/10 + 1/15 = 1/6 of the job, so 6 days.' },
  { section: 'QUANT', topic: 'Time and work', difficulty: 1, stem: '6 people finish a task in 12 days. How many days would 9 people take, working at the same rate?', options: ['6', '8', '9', '10'], answerIndex: 1, explanation: 'The task is 6 × 12 = 72 person-days. With 9 people: 72 ÷ 9 = 8 days.' },
  { section: 'QUANT', topic: 'Time, speed and distance', difficulty: 1, stem: 'A bus travels at 60 km/h for 2.5 hours. How far does it go?', options: ['120 km', '140 km', '150 km', '160 km'], answerIndex: 2, explanation: 'Distance = speed × time = 60 × 2.5 = 150 km.' },
  { section: 'QUANT', topic: 'Time, speed and distance', difficulty: 3, stem: 'A cyclist goes to a town at 40 km/h and returns along the same road at 60 km/h. What is the average speed for the round trip?', options: ['48 km/h', '50 km/h', '52 km/h', '45 km/h'], answerIndex: 0, explanation: 'For equal distances the average is 2 × 40 × 60 ÷ (40 + 60) = 48 km/h, not the simple average of 50.' },
  { section: 'QUANT', topic: 'Time, speed and distance', difficulty: 2, stem: 'A 200 m long train runs at 72 km/h. How long does it take to pass a signal pole?', options: ['8 seconds', '10 seconds', '12 seconds', '14 seconds'], answerIndex: 1, explanation: '72 km/h = 20 m/s. The train must cover its own length: 200 ÷ 20 = 10 seconds.' },
  { section: 'QUANT', topic: 'Ratios', difficulty: 1, stem: '₹1,200 is shared in the ratio 3 : 5. What is the larger share?', options: ['₹450', '₹700', '₹750', '₹800'], answerIndex: 2, explanation: 'There are 3 + 5 = 8 parts, each worth 150. The larger share is 5 × 150 = ₹750.' },
  { section: 'QUANT', topic: 'Ratios', difficulty: 1, stem: 'In a class the ratio of boys to girls is 4 : 3. There are 28 boys. How many girls are there?', options: ['18', '21', '24', '25'], answerIndex: 1, explanation: '4 parts = 28, so one part = 7. Girls are 3 × 7 = 21.' },
  { section: 'QUANT', topic: 'Averages', difficulty: 2, stem: 'Five numbers average 16. When one is removed, the other four average 15. Which number was removed?', options: ['15', '18', '20', '24'], answerIndex: 2, explanation: 'Total of five = 80, total of four = 60, so the removed number is 20.' },
  { section: 'QUANT', topic: 'Averages', difficulty: 2, stem: 'Your average over three tests is 72. What must you score in the fourth to average 75?', options: ['78', '80', '84', '90'], answerIndex: 2, explanation: 'You need 4 × 75 = 300 in total and have 3 × 72 = 216, so the fourth test needs 84.' },
  { section: 'QUANT', topic: 'Probability', difficulty: 1, stem: 'A fair six-sided die is rolled once. What is the probability of an even number?', options: ['1/3', '1/2', '2/3', '1/6'], answerIndex: 1, explanation: 'Three of the six faces (2, 4, 6) are even: 3/6 = 1/2.' },
  { section: 'QUANT', topic: 'Probability', difficulty: 2, stem: 'Two fair coins are tossed. What is the probability of at least one head?', options: ['1/4', '1/2', '3/4', '1'], answerIndex: 2, explanation: 'The only way to get no head is tails–tails, with probability 1/4. So at least one head = 1 − 1/4 = 3/4.' },
  { section: 'QUANT', topic: 'Probability', difficulty: 1, stem: 'A bag holds 3 red and 5 blue balls. One ball is drawn at random. What is the probability it is red?', options: ['3/5', '3/8', '5/8', '1/3'], answerIndex: 1, explanation: '3 red out of 8 balls in total: 3/8.' },

  /* --- reasoning ---------------------------------------------------------- */
  { section: 'REASONING', topic: 'Number series', difficulty: 1, stem: 'What comes next: 3, 7, 15, 31, ?', options: ['47', '55', '63', '62'], answerIndex: 2, explanation: 'Each term is double the last plus one: 31 × 2 + 1 = 63.' },
  { section: 'REASONING', topic: 'Number series', difficulty: 2, stem: 'What comes next: 2, 6, 12, 20, 30, ?', options: ['36', '40', '42', '44'], answerIndex: 2, explanation: 'The gaps grow by 2 each time (4, 6, 8, 10, 12), so 30 + 12 = 42. Each term is also n × (n + 1).' },
  { section: 'REASONING', topic: 'Number series', difficulty: 1, stem: 'What comes next: 1, 4, 9, 16, 25, ?', options: ['30', '35', '36', '49'], answerIndex: 2, explanation: 'These are squares: 1², 2², 3² … so next is 6² = 36.' },
  { section: 'REASONING', topic: 'Letter series', difficulty: 2, stem: 'What comes next: A, C, F, J, ?', options: ['M', 'N', 'O', 'P'], answerIndex: 2, explanation: 'The jumps grow by one: +2, +3, +4, then +5. J + 5 = O.' },
  { section: 'REASONING', topic: 'Coding-decoding', difficulty: 1, stem: 'If CAT is written as DBU, how is DOG written?', options: ['EPH', 'CNF', 'EOH', 'FPI'], answerIndex: 0, explanation: 'Each letter moves one step forward: D→E, O→P, G→H.' },
  { section: 'REASONING', topic: 'Coding-decoding', difficulty: 1, stem: 'In a code, every letter is replaced by the letter after it. The code word is HPPE. What is the original word?', options: ['GOOD', 'FOOD', 'HOOD', 'GOLD'], answerIndex: 0, explanation: 'Step each letter back by one: H→G, P→O, P→O, E→D gives GOOD.' },
  { section: 'REASONING', topic: 'Blood relations', difficulty: 2, stem: 'Pointing to a man, Riya says, “His mother is the only daughter of my mother.” How is the man related to Riya?', options: ['Brother', 'Son', 'Nephew', 'Cousin'], answerIndex: 1, explanation: 'The only daughter of Riya’s mother is Riya herself, so she is his mother and he is her son.' },
  { section: 'REASONING', topic: 'Blood relations', difficulty: 2, stem: 'A is B’s brother. C is A’s father. D is C’s mother. How is B related to D?', options: ['Grandson', 'Granddaughter', 'Grandchild', 'Son'], answerIndex: 2, explanation: 'B is C’s child and D is C’s mother, so B is D’s grandchild. B’s gender is never stated, so only “grandchild” is certain.' },
  { section: 'REASONING', topic: 'Directions', difficulty: 2, stem: 'Meera walks 5 km north, turns right and walks 3 km, then turns right again and walks 5 km. Where is she now compared with her starting point?', options: ['3 km west', '3 km east', '5 km north', '8 km east'], answerIndex: 1, explanation: 'North 5, then right (east) 3, then right (south) 5 brings her back level with the start, 3 km to the east.' },
  { section: 'REASONING', topic: 'Directions', difficulty: 1, stem: 'You face north, turn 90° clockwise twice, then 90° anticlockwise once. Which way do you face?', options: ['North', 'South', 'East', 'West'], answerIndex: 2, explanation: 'North → east → south, then one turn back anticlockwise returns you to east.' },
  { section: 'REASONING', topic: 'Syllogisms', difficulty: 3, stem: 'All engineers are graduates. Some graduates are artists. Does it follow that some engineers are artists?', options: ['Definitely true', 'Definitely false', 'Cannot be determined', 'True only if every artist is a graduate'], answerIndex: 2, explanation: 'The artists could all be graduates who are not engineers. Nothing links engineers to artists, so it cannot be determined.' },
  { section: 'REASONING', topic: 'Syllogisms', difficulty: 2, stem: 'All pens are tools. No tool is a toy. Which conclusion follows?', options: ['No pen is a toy', 'Some pens are toys', 'All toys are tools', 'None of these follows'], answerIndex: 0, explanation: 'Every pen is inside “tools”, and nothing in “tools” is a toy, so no pen can be a toy.' },
  { section: 'REASONING', topic: 'Seating arrangement', difficulty: 2, stem: 'A, B, C, D and E sit in a row facing north. C is in the middle. A is at the left end. B sits immediately right of C. E is not at an end. Who sits at the right end?', options: ['B', 'D', 'E', 'A'], answerIndex: 1, explanation: 'A is 1st and C is 3rd, so B is 4th. E is not at an end, so E is 2nd, which leaves D at the right end.' },
  { section: 'REASONING', topic: 'Seating arrangement', difficulty: 2, stem: 'P, Q, R and S sit around a square table facing the centre. P is opposite R. Q is on P’s immediate left. Who is on P’s immediate right?', options: ['Q', 'R', 'S', 'Cannot say'], answerIndex: 2, explanation: 'P’s two neighbours are the two people not opposite: Q and S. Q is on the left, so S is on the right.' },
  { section: 'REASONING', topic: 'Odd one out', difficulty: 1, stem: 'Which is the odd one out: 121, 144, 169, 190, 225?', options: ['121', '169', '190', '225'], answerIndex: 2, explanation: 'All the others are perfect squares (11², 12², 13², 15²). 190 is not.' },
  { section: 'REASONING', topic: 'Analogies', difficulty: 1, stem: 'Book is to author as building is to ?', options: ['Engineer', 'Architect', 'Mason', 'Owner'], answerIndex: 1, explanation: 'An author designs and writes a book; an architect designs a building.' },

  /* --- verbal --------------------------------------------------------------- */
  { section: 'VERBAL', topic: 'Grammar', difficulty: 2, stem: 'Neither the students nor the teacher ___ ready.', options: ['were', 'was', 'are', 'have been'], answerIndex: 1, explanation: 'With “neither … nor” the verb agrees with the nearer subject, “the teacher”, which is singular: was.' },
  { section: 'VERBAL', topic: 'Grammar', difficulty: 1, stem: 'She has been working here ___ 2022.', options: ['for', 'since', 'from', 'by'], answerIndex: 1, explanation: 'Use “since” with a starting point in time and “for” with a length of time.' },
  { section: 'VERBAL', topic: 'Grammar', difficulty: 2, stem: 'If I ___ you, I would accept the offer.', options: ['am', 'was', 'were', 'will be'], answerIndex: 2, explanation: 'An imagined situation takes “were” for every subject: “If I were you”.' },
  { section: 'VERBAL', topic: 'Grammar', difficulty: 1, stem: 'The manager asked us to ___ the report by Friday.', options: ['submit', 'submitting', 'submitted', 'submits'], answerIndex: 0, explanation: '“Asked us to” is followed by the base form of the verb: submit.' },
  { section: 'VERBAL', topic: 'Synonyms', difficulty: 1, stem: 'Choose the word closest in meaning to DILIGENT.', options: ['Lazy', 'Hard-working', 'Clever', 'Careless'], answerIndex: 1, explanation: 'Diligent means careful and hard-working.' },
  { section: 'VERBAL', topic: 'Synonyms', difficulty: 1, stem: 'Choose the word closest in meaning to CONCISE.', options: ['Brief', 'Detailed', 'Confusing', 'Loud'], answerIndex: 0, explanation: 'Concise means saying a lot in few words: brief.' },
  { section: 'VERBAL', topic: 'Synonyms', difficulty: 2, stem: 'Choose the word closest in meaning to CANDID.', options: ['Frank', 'Secretive', 'Polite', 'Nervous'], answerIndex: 0, explanation: 'Candid means honest and direct: frank.' },
  { section: 'VERBAL', topic: 'Antonyms', difficulty: 1, stem: 'Choose the word most opposite in meaning to SCARCE.', options: ['Rare', 'Plentiful', 'Expensive', 'Small'], answerIndex: 1, explanation: 'Scarce means in short supply; its opposite is plentiful.' },
  { section: 'VERBAL', topic: 'Sentence correction', difficulty: 1, stem: 'Which sentence is correct?', options: ['He don’t know the answer.', 'He doesn’t knows the answer.', 'He doesn’t know the answer.', 'He not know the answer.'], answerIndex: 2, explanation: 'After “doesn’t” the verb takes its base form: “doesn’t know”.' },
  { section: 'VERBAL', topic: 'Sentence correction', difficulty: 2, stem: 'Each of the candidates ___ given a form.', options: ['were', 'was', 'are', 'have'], answerIndex: 1, explanation: '“Each” is singular, so the verb is singular: was.' },
  { section: 'VERBAL', topic: 'Sentence correction', difficulty: 2, stem: 'Which is the correct way to end a formal email?', options: ['I look forward to hearing from you.', 'I look forward to hear from you.', 'I am looking forward to hear from you.', 'I look forward for hearing from you.'], answerIndex: 0, explanation: 'In “look forward to”, “to” is a preposition, so it is followed by the -ing form: hearing.' },
  { section: 'VERBAL', topic: 'Reading comprehension', difficulty: 2, stem: `${PASSAGE}\n\nWhat is the main point of the passage?`, options: ['Bakeries should close earlier', 'Giving away leftovers helped the bakery learn what to bake less of', 'The shelter asked for more bread', 'Customers in Nashik prefer cakes'], answerIndex: 1, explanation: 'The passage is about how tracking the donated bread showed what customers did not buy, so the bakery baked less.' },
  { section: 'VERBAL', topic: 'Reading comprehension', difficulty: 1, stem: `${PASSAGE}\n\nRoughly how much less did the bakery end up baking?`, options: ['About 5%', 'About 20%', 'About half', 'It did not change'], answerIndex: 1, explanation: '“About a fifth less” is about 20%.' },
  { section: 'VERBAL', topic: 'Reading comprehension', difficulty: 2, stem: `${PASSAGE}\n\nHow does the owner now mainly see the donations?`, options: ['As a tax benefit', 'As a source of useful information', 'As a marketing campaign', 'As a burden'], answerIndex: 1, explanation: 'The owner calls them the bakery’s “most useful source of data”.' },

  /* --- technical ------------------------------------------------------------ */
  { section: 'TECHNICAL', topic: 'DBMS', difficulty: 1, stem: 'What does SQL stand for?', options: ['Simple Query Language', 'Structured Query Language', 'Sequential Question Language', 'Standard Quick Logic'], answerIndex: 1, explanation: 'SQL is Structured Query Language, used to work with relational databases.' },
  { section: 'TECHNICAL', topic: 'DBMS', difficulty: 2, stem: 'Which SQL clause filters groups after they have been aggregated?', options: ['WHERE', 'GROUP BY', 'HAVING', 'ORDER BY'], answerIndex: 2, explanation: 'WHERE filters rows before grouping; HAVING filters the groups after aggregation, e.g. HAVING COUNT(*) > 5.' },
  { section: 'TECHNICAL', topic: 'DBMS', difficulty: 1, stem: 'A primary key in a table …', options: ['can repeat across rows', 'uniquely identifies each row and cannot be NULL', 'must always be a number', 'is optional and rarely used'], answerIndex: 1, explanation: 'A primary key is unique for every row and may not be NULL. It can be text or a combination of columns.' },
  { section: 'TECHNICAL', topic: 'DBMS', difficulty: 2, stem: 'The main aim of normalising a database is to …', options: ['make the CPU faster', 'reduce repeated (redundant) data', 'encrypt the data', 'increase the storage used'], answerIndex: 1, explanation: 'Normalisation splits data so each fact is stored once, which avoids redundancy and update mistakes.' },
  { section: 'TECHNICAL', topic: 'Data structures', difficulty: 1, stem: 'A stack follows which order?', options: ['First in, first out', 'Last in, first out', 'Random order', 'Sorted order'], answerIndex: 1, explanation: 'A stack is last in, first out (LIFO) - like a pile of plates.' },
  { section: 'TECHNICAL', topic: 'Data structures', difficulty: 1, stem: 'Print jobs should be handled in the order they arrive. Which structure fits best?', options: ['Stack', 'Queue', 'Tree', 'Hash map'], answerIndex: 1, explanation: 'A queue is first in, first out (FIFO), which keeps arrival order.' },
  { section: 'TECHNICAL', topic: 'Algorithms', difficulty: 2, stem: 'What is the time complexity of binary search on a sorted array of n items?', options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'], answerIndex: 1, explanation: 'Each step halves the search space, so it takes about log₂ n steps: O(log n).' },
  { section: 'TECHNICAL', topic: 'Programming', difficulty: 1, stem: 'In Python, what does this print?\n\nfor i in range(3):\n    print(i)', options: ['1 2 3', '0 1 2', '0 1 2 3', '1 2'], answerIndex: 1, explanation: 'range(3) starts at 0 and stops before 3, giving 0, 1 and 2.' },
  { section: 'TECHNICAL', topic: 'Programming', difficulty: 1, stem: 'Using integer division, what is 7 divided by 2?', options: ['3.5', '3', '4', '2'], answerIndex: 1, explanation: 'Integer division drops the remainder: 7 ÷ 2 = 3 remainder 1.' },
  { section: 'TECHNICAL', topic: 'Programming', difficulty: 2, stem: 'Which idea lets a subclass provide its own version of a method it inherits?', options: ['Overloading', 'Overriding', 'Encapsulation', 'Abstraction'], answerIndex: 1, explanation: 'Overriding replaces an inherited method in the subclass. Overloading is several methods with the same name but different parameters.' },
  { section: 'TECHNICAL', topic: 'Operating systems', difficulty: 2, stem: 'Two processes each hold a resource the other needs, so both wait forever. This is called …', options: ['Thrashing', 'Deadlock', 'Paging', 'Starvation'], answerIndex: 1, explanation: 'A deadlock is a cycle of processes each waiting for the other to release something.' },
  { section: 'TECHNICAL', topic: 'Operating systems', difficulty: 2, stem: 'Virtual memory lets a computer …', options: ['run programs larger than physical RAM by using disk space', 'increase the CPU’s clock speed', 'store files permanently', 'connect to the internet'], answerIndex: 0, explanation: 'Virtual memory maps parts of a program to disk so programs can use more memory than the RAM installed.' },
  { section: 'TECHNICAL', topic: 'Networks', difficulty: 1, stem: 'What is the default port for plain HTTP?', options: ['21', '25', '80', '443'], answerIndex: 2, explanation: 'HTTP uses port 80. HTTPS uses 443, FTP 21 and SMTP 25.' },
  { section: 'TECHNICAL', topic: 'Tools', difficulty: 1, stem: 'Which Git command records your staged changes in the repository history?', options: ['git push', 'git commit', 'git add', 'git clone'], answerIndex: 1, explanation: 'git add stages changes, git commit records them, and git push sends commits to a remote.' },
];
