-- AlterTable
ALTER TABLE `Job` MODIFY `jobType` VARCHAR(191) NOT NULL DEFAULT 'FULL_TIME';

-- AlterTable
ALTER TABLE `JobOption` ADD COLUMN `convertsToPpo` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `paysStipend` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `kind` ENUM('EMPLOYMENT_TYPE', 'WORK_MODE', 'ROUND_TYPE', 'ROUND_MODE') NOT NULL;

